<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="survey" nsURI="http://survey/1.0" nsPrefix="survey">
  <eClassifiers xsi:type="ecore:EClass" name="Survey">
    <eStructuralFeatures xsi:type="ecore:EReference" name="consists of" lowerBound="1"
        upperBound="-1" eType="#//Question" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TextQuestion" eSuperTypes="#//Question"/>
  <eClassifiers xsi:type="ecore:EClass" name="RadioQuestion" eSuperTypes="#//Question">
    <eStructuralFeatures xsi:type="ecore:EReference" name="has" lowerBound="1" upperBound="-1"
        eType="#//AnswerOption" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="other" lowerBound="1" eType="#//TextQuestion"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SelectQuestion" eSuperTypes="#//Question">
    <eStructuralFeatures xsi:type="ecore:EReference" name="has" lowerBound="1" upperBound="-1"
        eType="#//AnswerOption" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="" eType="#//SelectQuestion"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="other" lowerBound="1" eType="#//TextQuestion"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnswerOption">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="answer" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="conditional" lowerBound="1"
        eType="#//Question" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Question">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mand" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="question" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
